#!/bin/sh

cd $(dirname "$0")

# kill led ----------------------------------------------------
export PATH=/mnt/SDCARD/trimui/bin:$PATH
leds_off

# recover from readonly SD card -------------------------------
touch /mnt/writetest
sync
if [ -f /mnt/writetest ] ; then
	rm -f /mnt/writetest
else
	e2fsck -p /dev/root > /mnt/SDCARD/RootRecovery.txt
	reboot
fi

# launch keymon -----------------------------------------------
export LD_LIBRARY_PATH=/usr/trimui/lib
keymon &

# restore settings --------------------------------------------
restore_brightness
restore_volume

# prepare picoarch --------------------------------------------
export HOME=/mnt/SDCARD/Roms
mkdir -p "$HOME/.picoarch"

# prepare dummy recent core -----------------------------------
if [ !-f ./recent_libretro.so]; then
	touch ./recent_libretro.so
fi

# copy over bios if necessary ---------------------------------
# TODO: can cause hang if you launch a core while still copying
# if [ ! -f ./system/gb_bios.bin ]; then
# 	cp -rf /mnt/SDCARD/RetroArch/.retroarch/system ./ &
# fi

echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo A,B,X,Y,L,R > /sys/module/gpio_keys_polled/parameters/button_config

# launch picoarch ---------------------------------------------
while :; do
	if [ -f ./picoarch.txt ]; then
		mv ./picoarch.txt ./picoarch-previous.txt
	fi
		
	./picoarch &> ./picoarch.txt
	sync
	
	# launch Commander ----------------------------------------
	if [ -f /tmp/commander ]; then
		rm /tmp/commander
		if [ -f /mnt/SDCARD/Apps/Commander/launch.sh ]; then
			/mnt/SDCARD/Apps/Commander/launch.sh
		fi
		sync
	fi
done