#!/bin/sh

cd $(dirname "$0")

# kill led ----------------------------------------------------
echo 0 > /sys/devices/platform/sunxi-led/leds/led1/brightness
echo 0 > /sys/devices/platform/sunxi-led/leds/led2/brightness
echo 0 > /sys/devices/platform/sunxi-led/leds/led3/brightness

# recover from readonly SD card -------------------------------
touch /mnt/writetest
sync
if [ -f /mnt/writetest ] ; then
	rm -f /mnt/writetest
else
	e2fsck -p /dev/root > /mnt/SDCARD/RootRecovery.txt
	reboot
fi

# launch keymon -----------------------------------------------
export LD_LIBRARY_PATH=/usr/trimui/lib
keymon &

# restore brightness ------------------------------------------
MIN_BRIGHT=30 # 10 is actual min
MAX_BRIGHT=255
BRIGHT=$(cat /mnt/UDISK/system.json | jsonfilter -e "@.brightness")
BRIGHT=$(( $BRIGHT * ($MAX_BRIGHT-$MIN_BRIGHT) / 10 + $MIN_BRIGHT ))
/usr/trimui/bin/iodisp 0 $BRIGHT

# restore volume ----------------------------------------------
VOL=$(cat /mnt/UDISK/system.json | jsonfilter -e "@.vol")
# VOL=$(( $VOL * 31 / 20 ))
# a bug in keymon maxes vol at 10 instead of the 20
if [ $VOL -gt 10 ]; then
	VOL=10
fi
VOL=$(( $VOL * 31 / 10 ))
amixer sset 'Lineout volume' $VOL

export HOME=/mnt/SDCARD/Roms
mkdir -p "$HOME/.picoarch"

# prepare dummy recent core -----------------------------------
if [ !-f ./recent_libretro.so]; then
	touch ./recent_libretro.so
fi

# copy over bios if necessary ---------------------------------
# TODO: can cause hang if you launch a core while still copying
# if [ ! -f ./system/gb_bios.bin ]; then
# 	cp -rf /mnt/SDCARD/RetroArch/.retroarch/system ./ &
# fi

echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo A,B,X,Y,L,R > /sys/module/gpio_keys_polled/parameters/button_config

# launch picoarch ---------------------------------------------
while :; do
	if [ -f ./picoarch.txt ]; then
		mv ./picoarch.txt ./picoarch-previous.txt
	fi
		
	./picoarch &> ./picoarch.txt
	sync
	
	if [ -f /tmp/commander ]; then
		rm /tmp/commander
		if [ -f /mnt/SDCARD/Apps/Commander/launch.sh ]; then
			/mnt/SDCARD/Apps/Commander/launch.sh
		fi
		sync
	fi
done